### ISSUE TITLE
bug: request to upgrade rocket version

### ISSUE THREAD

**Issue by carrascomj** [steadylearner/Rust-Web-App#1]
#### System info
* cargo 1.44.0-nightly
* rustup 1.21.1

#### Problem
Running `cargo +nightly run` gave me an unresolved import of `FnBox` ([which was apparently removed in Rust 1.37](https://stackoverflow.com/questions/57943669/why-rust-fnbox-example-error-no-fnbox-in-boxed)).

#### Proposed solution
Upgrading `rocket` and `rocket_contrib` to **0.4.4** solved the issue. Would it be possible to upgrade it in the _Cargo.toml_ of the repository?

By the way, thank you for this awesome resource :).

**Comment by steadylearner** [comment]
I will update that. Thanks.
